name: Setup Restic
description: Setup/Install Restic for GitHub Actions
branding:
  icon: life-buoy
  color: yellow
  
runs:
  using: composite
  steps:
    - name: Download Restic for Linux
      if: runner.os == 'Linux'
      shell: bash
      working-directory: ${{ runner.temp }}
      run: $GITHUB_ACTION_PATH/scripts/Linux.sh
      
    - name: Download Restic for Windows
      if: runner.os == 'Windows'
      shell: pwsh
      working-directory: ${{ runner.temp }}
      run: '& $env:GITHUB_ACTION_PATH\scripts\Windows.ps1'
      
    - name: Download Restic for macOS
      if: runner.os == 'macOS'
      shell: bash
      working-directory: ${{ runner.temp }}
      run: $GITHUB_ACTION_PATH/scripts/macOS.sh
      
    - name: Install Restic on tool cache
      uses: AnimMouse/tool-cache@v1
      with:
        folder_name: Restic